name: Deploy to Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Deploy to Website
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-website.com 'cd /path/to/website && git pull origin main'
